# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vizid < Formula
  desc "VIZID: visual, sortable timestamps + IDs"
  homepage "https://github.com/rtluckie/gVIZID"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rtluckie/vizid/releases/download/0.2.0/vizid_0.2.0_darwin_amd64.tar.gz"
      sha256 "7f530faf6de9c464b17a43d546cf54c73b7c9c1e5c89bc72ab11dbb494b2385e"

      def install
        bin.install "vizid"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rtluckie/vizid/releases/download/0.2.0/vizid_0.2.0_darwin_arm64.tar.gz"
      sha256 "d8ed8a2265a711fa03677ad05ab6456d00f400e1c50a3930554dcdfe62618ce1"

      def install
        bin.install "vizid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rtluckie/vizid/releases/download/0.2.0/vizid_0.2.0_linux_amd64.tar.gz"
      sha256 "90ddf2a57e5db7cd5ef71f578d528bb5432ba65474adc592a4973745ddef046c"
      def install
        bin.install "vizid"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rtluckie/vizid/releases/download/0.2.0/vizid_0.2.0_linux_arm64.tar.gz"
      sha256 "deb39e6b494e9f60570937d2cf2daf629fcc79cfd91f8cef58a4c2d89a2bf768"
      def install
        bin.install "vizid"
      end
    end
  end
end
