# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vizid < Formula
  desc "VIZID: visual, sortable timestamps + IDs"
  homepage "https://github.com/rtluckie/gVIZID"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rtluckie/vizid/releases/download/0.1.1/vizid_0.1.1_darwin_amd64.tar.gz"
      sha256 "3c15bbf1c47f1f3eeb1214536a648af1c56358c956d0d75641e329ed3d78a335"

      def install
        bin.install "vizid"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rtluckie/vizid/releases/download/0.1.1/vizid_0.1.1_darwin_arm64.tar.gz"
      sha256 "efe309b7fbffa49629917d9d864cab0142bfd39c80331c2cfe2744785ee2ae5f"

      def install
        bin.install "vizid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rtluckie/vizid/releases/download/0.1.1/vizid_0.1.1_linux_amd64.tar.gz"
      sha256 "869fa979486d04bc831abbc2b9b360c5ae6b9deb9af5f472ead09c9146b3c55e"
      def install
        bin.install "vizid"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rtluckie/vizid/releases/download/0.1.1/vizid_0.1.1_linux_arm64.tar.gz"
      sha256 "9705942bdf68540f0a7a82aa8566e10755e0ed5aec682aabb45634c9f240e272"
      def install
        bin.install "vizid"
      end
    end
  end
end
