# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gvizid < Formula
  desc "VIZID: visual, sortable timestamps + IDs"
  homepage "https://github.com/rtluckie/gVIZID"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rtluckie/gVIZID/releases/download/0.1.0/gvizid_0.1.0_darwin_amd64.tar.gz"
      sha256 "936fd8c05f4febab58e4fd246108c0d5f47269f5af7ea78924ad42d871ea0f63"

      def install
        bin.install "gvizid"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rtluckie/gVIZID/releases/download/0.1.0/gvizid_0.1.0_darwin_arm64.tar.gz"
      sha256 "d5c8c7c28b919e611a76dc1438bd5d74e20f6aed49621aa7d8acdde215a99517"

      def install
        bin.install "gvizid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rtluckie/gVIZID/releases/download/0.1.0/gvizid_0.1.0_linux_amd64.tar.gz"
      sha256 "929676cbb1f976cf462b92ef20c89e9e1c7bc156df42e3248834d69afe6dc94b"
      def install
        bin.install "gvizid"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rtluckie/gVIZID/releases/download/0.1.0/gvizid_0.1.0_linux_arm64.tar.gz"
      sha256 "1bf9cfa7d0d7502590ba253df972d7251671787899bbe6e850f8c530311486d2"
      def install
        bin.install "gvizid"
      end
    end
  end
end
